package db

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5/pgxpool"
)

var Pool *pgxpool.Pool

func InitDB(ctx context.Context, dbURL string) error {

	Config, err := pgxpool.ParseConfig(dbURL)

	if err != nil {
		return errors.New("failed to parse database config")
	}

	Pool, err = pgxpool.NewWithConfig(ctx, Config)

	if err != nil {
		return errors.New("failed to create database connection pool")
	}

	err = Pool.Ping(ctx)

	if err != nil {
		return errors.New("failed to connect to database")
	}

	err = CreateTables(ctx)

	if err != nil {
		return errors.New("failed to create tables")
	}

	return nil
}

func GetDB() *pgxpool.Pool {
	return Pool
}

func CreateTables(ctx context.Context) error {
	// Check if all required tables exist
	var count int
	err := Pool.QueryRow(ctx, `SELECT COUNT(*) 
	FROM information_schema.tables
	WHERE table_schema = 'public' AND
	table_name IN ('users', 'clock_sessions', 'expense_categories', 'expenses')`).Scan(&count)

	if err != nil {
		return err
	}

	if count == 5 {
		fmt.Println("All tables already exist, skipping initialization")
		return nil
	}

	exec, err := Pool.Begin(ctx)

	if err != nil {
		return errors.New("could not create tables")
	}

	defer func() {
		_ = exec.Rollback(ctx)
	}()

	commands := []string{
		`CREATE TABLE IF NOT EXISTS users 
		(
			id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
			name TEXT NOT NULL,
			email TEXT UNIQUE NOT NULL,
			password TEXT NOT NULL,
			hourly_rate DECIMAL(10,2) DEFAULT 0.0 NOT NULL,
			created_at TIMESTAMPTZ DEFAULT NOW(),
			updated_at TIMESTAMPTZ DEFAULT NOW()
		)`,
		`CREATE TABLE IF NOT EXISTS clock_sessions 
		(
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			user_id	UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
			start_time TIMESTAMPTZ DEFAULT NOW() NOT NULL,
			end_time TIMESTAMPTZ NULL,
			overtime_multiplier DECIMAL(3,2) DEFAULT 1.0 NOT NULL
		)`,
		`CREATE TABLE IF NOT EXISTS expense_categories
		(
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name TEXT NOT NULL,
			color TEXT DEFAULT '#000000',
			created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
		)`,
		`CREATE TABLE IF NOT EXISTS expenses
		(
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
			category_id BIGINT REFERENCES expense_categories(id) ON DELETE CASCADE NOT NULL,
			amount DECIMAL(10,2) NOT NULL,
			description TEXT NULL,
			date DATE NOT NULL,
			created_at TIMESTAMPTZ DEFAULT NOW(),
			updated_at TIMESTAMPTZ DEFAULT NOW()
		)`,
		`CREATE TABLE IF NOT EXISTS plaid_items
		(
			id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
			user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
			access_token TEXT NOT NULL,
			item_id TEXT NOT NULL,
			institution_name TEXT NOT NULL,
			institution_id TEXT NOT NULL,
			accounts JSONB,
			created_at TIMESTAMPTZ DEFAULT NOW(),
			updated_at TIMESTAMPTZ DEFAULT NOW()
		)`,
	}

	for _, cmd := range commands {
		_, err = exec.Exec(ctx, cmd)
		if err != nil {
			return fmt.Errorf("error creating table: %v", err)
		}
	}

	err = exec.Commit(ctx)
	if err != nil {
		return fmt.Errorf("error committing tables: %v", err)
	}

	// Add accounts column to plaid_items if it doesn't exist (migration)
	_, err = Pool.Exec(ctx, `ALTER TABLE plaid_items ADD COLUMN IF NOT EXISTS accounts JSONB`)
	if err != nil {
		// Log but don't fail - column might already exist
		fmt.Printf("Note: Could not add accounts column (may already exist): %v\n", err)
	}

	fmt.Println("Tables created successfully")

	return nil
}
